service: ecs-service-switcher

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ecs:listClusters"
        - "ecs:describeClusters"
        - "ecs:listTagsForResource"
        - "ecs:listServices"
        - "ecs:updateService"
      Resource: "*"
  environment:
    tag_name: ecs-service-switcher-isenabled

package:
  exclude:
    - README.md

layers:
  ecsServiceSwitcher:
    path: layer

functions:
  start:
    handler: ecs-services/start.handler
    layers:
      - {Ref: EcsServiceSwitcherLambdaLayer}
    events:
      - schedule: cron(0 23 ? * SUN-THU *)
  stop:
    handler: ecs-services/stop.handler
    layers:
      - {Ref: EcsServiceSwitcherLambdaLayer}
    events:
      - schedule: cron(0 12 ? * MON-FRI *)
